# DataSets

In [83]:
import pandas as pd

In [84]:
# 임상데이터
meta_data= pd.read_excel('./data_files/S1.xlsx', sheet_name='220928_ACS-GM_MetaData')

In [87]:
# 임상 데이터 정보 
meta_data_info= pd.read_excel('./data_files/S1.xlsx', sheet_name='Data Dictionary')

In [182]:
meta_data_info.iloc[23, 1]

'1 = preclinical; 0 = healthy. Using rule: combined.Centiloid > 16.4 (corresponding to PiB > 1.42), or CSF AB42/AB40 < 0.0673 if PET data not available'

In [85]:
# 미생물별 미생물 구성 비교 
MetaPhlAn3 = pd.read_excel('./data_files/S2.xlsx', sheet_name='MetaPhlAn3')

In [86]:
# 미생물의 기능적 경로 및 유전자 비교 
HUMAaN_3_0 = pd.read_excel('./data_files/S2.xlsx', sheet_name='HUMAaN 3.0')

In [88]:
# 랜덤 포레스트 예측 성능 
RF_Predict_Perform = pd.read_excel('./data_files/S3.xlsx', sheet_name='Predictive Performance')

In [89]:
# 변수 중요도 (예측에 기여)
RF_val_import = pd.read_excel('./data_files/S3.xlsx', sheet_name='Variable Importance')

In [90]:
# 모델 데이터셋 정보 
RF_Dataset_info = pd.read_excel('./data_files/S3.xlsx', sheet_name='DataSet (Model) Dictionary')

In [91]:
# 실험자별 분류학적 상대적 풍부도 
meta_MetaPhlAn3 = pd.read_excel('./data_files/S4.xlsx', sheet_name='MetaPhlAn3', index_col="Unnamed: 0")

In [92]:
# 실험자별 분류학적 상대적 풍부도 
meta_HUMAaN_3_0 = pd.read_excel('./data_files/S4.xlsx', sheet_name='HUMAaN 3.0', index_col="Unnamed: 0")

In [93]:
# r코드에서 쓰인 임상 데이터
r_meta_data = pd.read_csv('./data_files/R_meta_caret_im.csv', index_col='Unnamed: 0')

In [94]:
# r코드에서 쓰인 taxa boruta data 
r_taxa_boruta_data = pd.read_csv('./data_files/R_taxa_caret_boruta.csv', index_col='Unnamed: 0')

# 데이터 전처리

In [45]:
total_Data = meta_data_info.copy()

In [46]:
total_Data.set_index("Variable", inplace=True)

In [47]:
meta_data.columns

Index(['Participant', 'Stool_Date_Collected', 'Age', 'Sex', 'Race',
       'Years Education', 'CDR.testdate', 'CDR', 'CSF_LP_DATE',
       'LUMIPULSE_CSF.ab42.ab40.ratio', 'LUMIPULSE_CSF_tTau',
       'LUMIPULSE_CSF_pTau', 'PET_Date_pib', 'Days.SincePETpib',
       'pib_fsuvr_rsf_tot_cortmean', 'Centiloid.PiB', 'PET_Date_av45',
       'Days.SincePETav45', 'av45_fsuvr_rsf_tot_cortmean', 'Centiloid.AV45',
       'combined.PET_Date', 'Tracer2Use', 'combined.Centiloid',
       'amyloid.positive.AF', 'PET_TAU_Date', 'Tauopathy', 'tau.positive.AF',
       'MRI_Date', 'CortSig_Thickness', 'MR_LV_RV_HIPPOCAMPUS', 'WMH_volume',
       'APOE', 'APOE4.status', 'Polygenic Risk Score', 'INT_PET', 'INT_CSF',
       'INT_MRI', 'INT_CDR', 'Interval_Measure_Amyloid',
       'Interval_Days_Amyloid', 'WEIGHT.lb', 'HEIGHT.in', 'BMI', 'Cancer',
       'Active.Depression', 'Hypercholesterolemia', 'Hypertension', 'Diabetes',
       'Liver.Disease', 'Alcohol.Abuse', 'Tobacco.Use.PastOrPresent',
       'Autoimmune.Disorder', 'Thyroid.Disease', 'Cardiovascular.Disease',
       'Reads', 'Richness', 'Shannon', 'Tax.PCoA1', 'Tax.PCoA2', 'FBratio',
       'Fnl.Richness', 'Fnl.Shannon', 'Fnl.PCoA1', 'Fnl.PCoA2'],
      dtype='object')

In [48]:
meta_columns_df = pd.DataFrame({'meta': meta_data.columns})

In [49]:
total_Data = pd.concat([total_Data.reset_index(drop=True), meta_columns_df.reset_index(drop=True)], axis=1)

In [50]:
total_Data.set_index(meta_data_info['Variable'], inplace=True)

In [51]:
len(meta_data.columns)

64

In [52]:
total_Data['meta'].notna().sum()

np.int64(64)

In [53]:
total_Data.iloc[62:65, :]

                                                 Description       meta
Variable
Fnl.PCoA1  sample coordinate on PCoA axis 1 (pathway prof...  Fnl.PCoA1
Fnl.PCoA2  sample coordinate on PCoA axis 2 (pathway prof...  Fnl.PCoA2
NaN                                                      NaN        NaN

In [54]:
r_meta_data.columns

Index(['amyloid.positive.AF', 'PET_amyloid', 'CSF.ratio.ab42.ab40', 'PET.Tau',
       'CSF.ptau', 'CSF.ttau', 'WMH_volume', 'Cort.Signature',
       'Hippocampus.Volume', 'Polygenic.Risk.Score', 'APOE4.status', 'Age',
       'Sex', 'Race', 'Years.Education', 'BMI', 'Hypertension', 'Diabetes',
       'IntervalDays.PET', 'IntervalDays.CSF', 'IntervalDays.MRI'],
      dtype='object')

In [ ]:
r_meta_data

In [58]:
len(r_meta_data.columns)

21

In [59]:
meta_data[['Participant','MR_LV_RV_HIPPOCAMPUS']]

     Participant  MR_LV_RV_HIPPOCAMPUS
0          11680                6328.0
1          16564                5880.4
2          16644                8696.4
3          22647                5649.2
4          24238                7460.9
..           ...                   ...
159        69158                   NaN
160        69208                6024.6
161        85150                7784.8
162        86001                7679.3
163        86403                7525.6

[164 rows x 2 columns]

In [60]:
r_meta_data['Hippocampus.Volume']

86403    7525.6
86001    7679.3
85150    7784.8
69208    6024.6
69158    7792.0
          ...
24238    7460.9
22647    5649.2
16644    8696.4
16564    5880.4
11680    6328.0
Name: Hippocampus.Volume, Length: 164, dtype: float64

In [61]:
meta_data.columns

Index(['Participant', 'Stool_Date_Collected', 'Age', 'Sex', 'Race',
       'Years Education', 'CDR.testdate', 'CDR', 'CSF_LP_DATE',
       'LUMIPULSE_CSF.ab42.ab40.ratio', 'LUMIPULSE_CSF_tTau',
       'LUMIPULSE_CSF_pTau', 'PET_Date_pib', 'Days.SincePETpib',
       'pib_fsuvr_rsf_tot_cortmean', 'Centiloid.PiB', 'PET_Date_av45',
       'Days.SincePETav45', 'av45_fsuvr_rsf_tot_cortmean', 'Centiloid.AV45',
       'combined.PET_Date', 'Tracer2Use', 'combined.Centiloid',
       'amyloid.positive.AF', 'PET_TAU_Date', 'Tauopathy', 'tau.positive.AF',
       'MRI_Date', 'CortSig_Thickness', 'MR_LV_RV_HIPPOCAMPUS', 'WMH_volume',
       'APOE', 'APOE4.status', 'Polygenic Risk Score', 'INT_PET', 'INT_CSF',
       'INT_MRI', 'INT_CDR', 'Interval_Measure_Amyloid',
       'Interval_Days_Amyloid', 'WEIGHT.lb', 'HEIGHT.in', 'BMI', 'Cancer',
       'Active.Depression', 'Hypercholesterolemia', 'Hypertension', 'Diabetes',
       'Liver.Disease', 'Alcohol.Abuse', 'Tobacco.Use.PastOrPresent',
       'Autoimmune.Disorder', 'Thyroid.Disease', 'Cardiovascular.Disease',
       'Reads', 'Richness', 'Shannon', 'Tax.PCoA1', 'Tax.PCoA2', 'FBratio',
       'Fnl.Richness', 'Fnl.Shannon', 'Fnl.PCoA1', 'Fnl.PCoA2'],
      dtype='object')

In [62]:
total_Data[total_Data['meta']=='INT_MRI']

                                               Description     meta r_meta
Variable
INT_MRI   interval (days) between stool collection and MRI  INT_MRI   None

In [63]:
len(r_meta_data.columns)

21

In [64]:
r_meta_data.columns

Index(['amyloid.positive.AF', 'PET_amyloid', 'CSF.ratio.ab42.ab40', 'PET.Tau',
       'CSF.ptau', 'CSF.ttau', 'WMH_volume', 'Cort.Signature',
       'Hippocampus.Volume', 'Polygenic.Risk.Score', 'APOE4.status', 'Age',
       'Sex', 'Race', 'Years.Education', 'BMI', 'Hypertension', 'Diabetes',
       'IntervalDays.PET', 'IntervalDays.CSF', 'IntervalDays.MRI'],
      dtype='object')

## 변수 선택

In [71]:
meta_data.columns

Index(['Participant', 'Stool_Date_Collected', 'Age', 'Sex', 'Race',
       'Years Education', 'CDR.testdate', 'CDR', 'CSF_LP_DATE',
       'LUMIPULSE_CSF.ab42.ab40.ratio', 'LUMIPULSE_CSF_tTau',
       'LUMIPULSE_CSF_pTau', 'PET_Date_pib', 'Days.SincePETpib',
       'pib_fsuvr_rsf_tot_cortmean', 'Centiloid.PiB', 'PET_Date_av45',
       'Days.SincePETav45', 'av45_fsuvr_rsf_tot_cortmean', 'Centiloid.AV45',
       'combined.PET_Date', 'Tracer2Use', 'combined.Centiloid',
       'amyloid.positive.AF', 'PET_TAU_Date', 'Tauopathy', 'tau.positive.AF',
       'MRI_Date', 'CortSig_Thickness', 'MR_LV_RV_HIPPOCAMPUS', 'WMH_volume',
       'APOE', 'APOE4.status', 'Polygenic Risk Score', 'INT_PET', 'INT_CSF',
       'INT_MRI', 'INT_CDR', 'Interval_Measure_Amyloid',
       'Interval_Days_Amyloid', 'WEIGHT.lb', 'HEIGHT.in', 'BMI', 'Cancer',
       'Active.Depression', 'Hypercholesterolemia', 'Hypertension', 'Diabetes',
       'Liver.Disease', 'Alcohol.Abuse', 'Tobacco.Use.PastOrPresent',
       'Autoimmune.Disorder', 'Thyroid.Disease', 'Cardiovascular.Disease',
       'Reads', 'Richness', 'Shannon', 'Tax.PCoA1', 'Tax.PCoA2', 'FBratio',
       'Fnl.Richness', 'Fnl.Shannon', 'Fnl.PCoA1', 'Fnl.PCoA2'],
      dtype='object')

In [72]:
rf_meta_variable_list = ['Age', 'Sex', 'Race', 'Years Education', 'LUMIPULSE_CSF.ab42.ab40.ratio', 'LUMIPULSE_CSF_tTau', 'LUMIPULSE_CSF_pTau', 'combined.Centiloid', 'amyloid.positive.AF', 'Tauopathy', 'CortSig_Thickness', 'MR_LV_RV_HIPPOCAMPUS', 'WMH_volume', 'APOE4.status', 'Polygenic Risk Score', 'BMI', 'Active.Depression', 'Hypertension', 'Diabetes', 'Alcohol.Abuse', 'Tobacco.Use.PastOrPresent', 'Autoimmune.Disorder', 'Cardiovascular.Disease']

In [73]:
co_mata_data = meta_data.copy()

In [74]:
co_mata_data.set_index('Participant', inplace=True)

In [75]:
rf_meta = co_mata_data[rf_meta_variable_list]

In [76]:
rf_taxa = r_taxa_boruta_data.copy()

## 결측치 처리

In [77]:
rf_meta.isnull().sum()[rf_meta.isnull().sum() > 0]

LUMIPULSE_CSF.ab42.ab40.ratio    18
LUMIPULSE_CSF_tTau               18
LUMIPULSE_CSF_pTau               18
combined.Centiloid               11
Tauopathy                        34
CortSig_Thickness                 7
MR_LV_RV_HIPPOCAMPUS              7
WMH_volume                        5
Polygenic Risk Score             64
Autoimmune.Disorder               1
dtype: int64

In [78]:
from sklearn.impute import KNNImputer

In [79]:
imputer = KNNImputer(n_neighbors=5)

In [80]:
columns_with_missing_values = ['LUMIPULSE_CSF.ab42.ab40.ratio', 'LUMIPULSE_CSF_tTau', 
                                'LUMIPULSE_CSF_pTau', 'combined.Centiloid', 
                                'Tauopathy', 'CortSig_Thickness', 
                                'MR_LV_RV_HIPPOCAMPUS', 'WMH_volume', 
                                'Polygenic Risk Score', 'Autoimmune.Disorder']

In [81]:
rf_meta.loc[:, columns_with_missing_values] = imputer.fit_transform(rf_meta[columns_with_missing_values])

In [82]:
rf_meta.isnull().sum()

Age                              0
Sex                              0
Race                             0
Years Education                  0
LUMIPULSE_CSF.ab42.ab40.ratio    0
LUMIPULSE_CSF_tTau               0
LUMIPULSE_CSF_pTau               0
combined.Centiloid               0
amyloid.positive.AF              0
Tauopathy                        0
CortSig_Thickness                0
MR_LV_RV_HIPPOCAMPUS             0
WMH_volume                       0
APOE4.status                     0
Polygenic Risk Score             0
BMI                              0
Active.Depression                0
Hypertension                     0
Diabetes                         0
Alcohol.Abuse                    0
Tobacco.Use.PastOrPresent        0
Autoimmune.Disorder              0
Cardiovascular.Disease           0
dtype: int64

# Random Forest

## 준비

In [95]:
import numpy as np
import pandas as pd

In [97]:
rf_taxa = pd.read_csv('./rf_taxa.csv', index_col='Unnamed: 0')

In [98]:
rf_meta = pd.read_csv('./rf_meta.csv', index_col='Participant')

In [99]:
rf_meta.columns

Index(['Age', 'Sex', 'Race', 'Years Education',
       'LUMIPULSE_CSF.ab42.ab40.ratio', 'LUMIPULSE_CSF_tTau',
       'LUMIPULSE_CSF_pTau', 'combined.Centiloid', 'amyloid.positive.AF',
       'Tauopathy', 'CortSig_Thickness', 'MR_LV_RV_HIPPOCAMPUS', 'WMH_volume',
       'APOE4.status', 'Polygenic Risk Score', 'INT_PET', 'INT_CSF', 'INT_MRI',
       'BMI', 'Active.Depression', 'Hypertension', 'Diabetes', 'Alcohol.Abuse',
       'Tobacco.Use.PastOrPresent', 'Autoimmune.Disorder',
       'Cardiovascular.Disease'],
      dtype='object')

In [100]:
r_meta_data.columns

Index(['amyloid.positive.AF', 'PET_amyloid', 'CSF.ratio.ab42.ab40', 'PET.Tau',
       'CSF.ptau', 'CSF.ttau', 'WMH_volume', 'Cort.Signature',
       'Hippocampus.Volume', 'Polygenic.Risk.Score', 'APOE4.status', 'Age',
       'Sex', 'Race', 'Years.Education', 'BMI', 'Hypertension', 'Diabetes',
       'IntervalDays.PET', 'IntervalDays.CSF', 'IntervalDays.MRI'],
      dtype='object')

    # Update feature names for ease of interpretation.
    meta.caret.im <- meta.caret.im %>% rename(PET_amyloid = combined.Centiloid, 
                                              CSF.ratio.ab42.ab40 = LUMIPULSE_CSF.ab42.ab40.ratio, 
                                              PET.Tau = Tauopathy,
                                              CSF.ptau = LUMIPULSE_CSF_pTau, 
                                              CSF.ttau = LUMIPULSE_CSF_tTau, 
                                              Cort.Signature = CortSig_Thickness,
                                              IntervalDays.PET = INT_PET, 
                                              IntervalDays.CSF = INT_CSF,
                                              IntervalDays.MRI = INT_MRI,
                                              Hippocampus.Volume = MR_LV_RV_HIPPOCAMPUS)

In [101]:
rf_meta.columns = [
    'Age', 'Sex', 'Race', 'Years.Education',
    'CSF.ratio.ab42.ab40', 'CSF.ttau',
    'CSF.ptau', 'PET_amyloid', 'amyloid.positive.AF',
    'PET.Tau', 'Cort.Signature', 'Hippocampus.Volume', 'WMH_volume',
    'APOE4.status', 'Polygenic.Risk.Score', 'INT_PET', 'INT_CSF', 'INT_MRI',
    'BMI', 'Active.Depression', 'Hypertension', 'Diabetes', 'Alcohol.Abuse',
    'Tobacco.Use.PastOrPresent', 'Autoimmune.Disorder',
    'Cardiovascular.Disease'
]

    A : PET_amyloid, CSF.ratio.ab42.ab40
    T : PET.Tau, CSF.ptau
    N : CSF.ttau, WMH_volume, Cort.Signature, Hippocampus.Volume
    G : Polygenic.Risk.Score, APOE4.status
    CC : Age, Sex, Race, Years Education, Hypertension, Diabetes, etc.

In [102]:
rf_meta.drop(columns=['INT_PET', 'INT_CSF', 'INT_MRI'], inplace=True)

In [103]:
rf_meta.columns

Index(['Age', 'Sex', 'Race', 'Years.Education', 'CSF.ratio.ab42.ab40',
       'CSF.ttau', 'CSF.ptau', 'PET_amyloid', 'amyloid.positive.AF', 'PET.Tau',
       'Cort.Signature', 'Hippocampus.Volume', 'WMH_volume', 'APOE4.status',
       'Polygenic.Risk.Score', 'BMI', 'Active.Depression', 'Hypertension',
       'Diabetes', 'Alcohol.Abuse', 'Tobacco.Use.PastOrPresent',
       'Autoimmune.Disorder', 'Cardiovascular.Disease'],
      dtype='object')

In [104]:
len(rf_meta.columns)

23

In [105]:
rf_data = pd.concat([rf_meta, rf_taxa], axis=1)

    시도해볼 조합 
    
    1. ALL
    2. ALL - A 
    3. G + CC 
    4. CC

In [106]:
from sklearn.model_selection import train_test_split

**train/validation 나눠줌**

In [107]:
varsnot2norm = ['Sex', 'Race', 'amyloid.positive.AF', 'APOE4.status', 'Diabetes', 'Hypertension', 'Diabetes', 'Alcohol.Abuse', 'Tobacco.Use.PastOrPresent', 'Autoimmune.Disorder', 'Cardiovascular.Disease', 'Active.Depression']

In [108]:
from sklearn.preprocessing import LabelEncoder

for col in varsnot2norm:
    le = LabelEncoder()
    rf_meta.loc[:, col] = le.fit_transform(rf_meta[col])

In [109]:
rf_meta_train, rf_meta_val = train_test_split(rf_meta, test_size=0.4, random_state=42)

In [110]:
rf_taxa_train = rf_taxa.loc[rf_meta_train.index]
rf_taxa_val = rf_taxa.loc[rf_meta_val.index]

**장내 미생물 데이터 O/X 함수**

In [111]:
def create_subsets(rf_meta, nullvars, rf_taxa):
    base_data = rf_meta.drop(columns=nullvars, errors='ignore')
    with_taxa_data = pd.concat([base_data, rf_taxa], axis=1)
    return {"Base": base_data, "WithTaxa": with_taxa_data}

In [112]:
A = ['PET_amyloid', 'CSF.ratio.ab42.ab40']
T = ['PET.Tau', 'CSF.ptau']
N = ['CSF.ttau', 'WMH_volume', 'Cort.Signature', 'Hippocampus.Volume']
G = ['APOE4.status', 'Polygenic.Risk.Score']

In [113]:
RF_Dataset_info

,DataSet (Model),Description,Model Abbr
0,Alpha,All biomarkers including amyloid,All
1,Beta,All biomarkers excluding amyloid,All -A
2,Zeta,Clinical Covariates + genetics + neurodegenera...,CC +GN
3,Eta,Clinical Covariates + genetics + tau,CC +GT
4,Theta,Clinical Covariates + neurodegeneration + tau,CC +NT
5,Nu,Clinical Covariates + tau,CC +T
6,Xi,Clinical Covariates + neurodegeneration,CC +N
7,Omicron,Clinical Covariates + Genetic Biomarkers,CC +G
8,Pi,Clinical Covariates Only,CC

In [114]:
RF_Dataset_info.iloc[[0,1,7,8], :].reset_index().iloc[:,1:]

  DataSet (Model)                               Description Model Abbr
0           Alpha          All biomarkers including amyloid        All
1            Beta          All biomarkers excluding amyloid     All -A
2         Omicron  Clinical Covariates + Genetic Biomarkers      CC +G
3              Pi                  Clinical Covariates Only         CC

    # default : CC 

    # Main Model
    Alpha = create_subsets(rf_meta, [], rf_taxa)           # ALL
    Beta = create_subsets(rf_meta, A, rf_taxa)             # ALL-A
    Omicron = create_subsets(rf_meta, A+T+N, rf_taxa)      # G
    Pi = create_subsets(rf_meta, A+T+N+G, rf_taxa)         # only CC

    # Supply Model 
    Zeta = create_subsets(rf_meta, A+T, rf_taxa)           # N+G
    Eta = create_subsets(rf_meta, A+N, rf_taxa)            # T+G
    Theta = create_subsets(rf_meta, A+G, rf_taxa)          # T+N
    Nu = create_subsets(rf_meta, A+N+G, rf_taxa)           # T
    Xi = create_subsets(rf_meta, A+T+G, rf_taxa)           # N

In [115]:
rf_meta_train.shape

(98, 23)

In [116]:
rf_meta_val.shape

(66, 23)

In [117]:
# Train
train_Alpha = create_subsets(rf_meta_train, [], rf_taxa_train)           # ALL
train_Beta = create_subsets(rf_meta_train, A, rf_taxa_train)             # ALL-A
train_Omicron = create_subsets(rf_meta_train, A + T + N, rf_taxa_train)  # G
train_Pi = create_subsets(rf_meta_train, A + T + N + G, rf_taxa_train)   # only CC

# Validation 
val_Alpha = create_subsets(rf_meta_val, [], rf_taxa_val)                 # ALL
val_Beta = create_subsets(rf_meta_val, A, rf_taxa_val)                   # ALL-A
val_Omicron = create_subsets(rf_meta_val, A + T + N, rf_taxa_val)        # G
val_Pi = create_subsets(rf_meta_val, A + T + N + G, rf_taxa_val)         # only CC

## 모델 시작

In [118]:
import random

In [119]:
random.seed(42)

In [120]:
from sklearn.model_selection import StratifiedKFold

In [121]:
cv10 = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)

In [122]:
from sklearn.preprocessing import StandardScaler

In [123]:
train_Alpha['WithTaxa'].columns

Index(['Age', 'Sex', 'Race', 'Years.Education', 'CSF.ratio.ab42.ab40',
       'CSF.ttau', 'CSF.ptau', 'PET_amyloid', 'amyloid.positive.AF', 'PET.Tau',
       'Cort.Signature', 'Hippocampus.Volume', 'WMH_volume', 'APOE4.status',
       'Polygenic.Risk.Score', 'BMI', 'Active.Depression', 'Hypertension',
       'Diabetes', 'Alcohol.Abuse', 'Tobacco.Use.PastOrPresent',
       'Autoimmune.Disorder', 'Cardiovascular.Disease',
       'k__Bacteria|p__Actinobacteria|c__Actinobacteria|o__Bifidobacteriales|f__Bifidobacteriaceae|g__Bifidobacterium|s__Bifidobacterium_longum',
       'k__Bacteria|p__Firmicutes|c__Clostridia|o__Clostridiales|f__Peptostreptococcaceae|g__Intestinibacter|s__Intestinibacter_bartlettii',
       'k__Bacteria|p__Firmicutes|c__Clostridia|o__Clostridiales|f__Oscillospiraceae|g__Oscillibacter|s__Oscillibacter_sp_57_20',
       'k__Bacteria|p__Firmicutes|c__Clostridia|o__Clostridiales|f__Ruminococcaceae|g__Ruthenibacterium|s__Ruthenibacterium_lactatiformans',
       'k__Bacteria|p__Firmicutes|c__Clostridia|o__Clostridiales|f__Lachnospiraceae|g__Blautia|s__Blautia_obeum',
       'k__Bacteria|p__Bacteroidetes|c__Bacteroidia|o__Bacteroidales|f__Tannerellaceae|g__Parabacteroides|s__Parabacteroides_merdae',
       'k__Bacteria|p__Bacteroidetes|c__Bacteroidia|o__Bacteroidales|f__Bacteroidaceae|g__Bacteroides|s__Bacteroides_dorei'],
      dtype='object')

In [124]:
train_Alpha['Base'].columns

Index(['Age', 'Sex', 'Race', 'Years.Education', 'CSF.ratio.ab42.ab40',
       'CSF.ttau', 'CSF.ptau', 'PET_amyloid', 'amyloid.positive.AF', 'PET.Tau',
       'Cort.Signature', 'Hippocampus.Volume', 'WMH_volume', 'APOE4.status',
       'Polygenic.Risk.Score', 'BMI', 'Active.Depression', 'Hypertension',
       'Diabetes', 'Alcohol.Abuse', 'Tobacco.Use.PastOrPresent',
       'Autoimmune.Disorder', 'Cardiovascular.Disease'],
      dtype='object')

In [125]:
def preprocess_data(data, varsnot2norm):
    scaler = StandardScaler()
    continuous_vars = data.columns.difference(varsnot2norm)

    data_scaled = data.copy()
    data_scaled[continuous_vars] = scaler.fit_transform(data[continuous_vars])
    
    return data_scaled

In [126]:
from sklearn.ensemble import RandomForestClassifier

In [127]:
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)

In [128]:
from sklearn.metrics import confusion_matrix

In [ ]:
from sklearn.model_selection import StratifiedKFold

results = []
model_name = ['Alpha', 'Beta', 'Omicron', 'Pi']
sub = ['Base', 'WithTaxa']

rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
n = 0
for i in model_name:
    for j in sub:
        for seed in range(1, 101):  # 100번 반복
            train_data = globals()[f"train_{i}"]
            val_data = globals()[f"val_{i}"]

            train_data_split, test_data_split = train_test_split(
                train_data[j], test_size=0.2, random_state=seed, stratify=train_data[j]['amyloid.positive.AF']
            )

            train_scaled = preprocess_data(train_data_split, varsnot2norm)
            test_scaled = preprocess_data(test_data_split, varsnot2norm)
            val_scaled = preprocess_data(val_data[j], varsnot2norm)

            X_train = train_scaled.drop(columns=['amyloid.positive.AF'])
            y_train = train_scaled['amyloid.positive.AF']
            X_test = test_scaled.drop(columns=['amyloid.positive.AF'])
            y_test = test_scaled['amyloid.positive.AF']
            X_val = val_scaled.drop(columns=['amyloid.positive.AF'])
            y_val = val_scaled['amyloid.positive.AF']
            
            # model train
            rf_model.fit(X_train, y_train)
            
            # Validation  Predict
            val_preds = rf_model.predict(X_val)
            val_accuracy = rf_model.score(X_val, y_val)

            cm = confusion_matrix(y_val, val_preds, labels=rf_model.classes_)
            tn, fp, fn, tp = cm.ravel()
            sensitivity = tp / (tp + fn) if (tp + fn) > 0 else 0
            specificity = tn / (tn + fp) if (tn + fp) > 0 else 0
            
            # CV 10 fold
            skf = StratifiedKFold(n_splits=10, shuffle=True, random_state=seed)  # 매 반복마다 다른 시드 적용
            cv_scores = cross_val_score(rf_model, X_train, y_train, cv=skf, scoring='accuracy')
            
            # test_accuracy
            test_accuracy = rf_model.score(X_test, y_test)

            results.append({
                "Model": f"{i}_{j}",
                "Seed": seed,
                "Mean CV Accuracy": cv_scores.mean(),
                "Test Accuracy": test_accuracy,
                "Validation Accuracy": val_accuracy,
                "Sensitivity": sensitivity,
                "Specificity": specificity,
                "CV Scores": list(cv_scores)
            })
            
            n += 1
            if n%10==0: print(n)

results_df = pd.DataFrame(results)

In [211]:
results_df.to_csv('result_df_without_INT.csv')

In [212]:
result_df_without_INT = pd.read_csv('result_df_without_INT.csv')      # INT_PET, INT_CSF, INT_MRI 포함 결과

In [173]:
results_df = pd.read_csv('result_df_without_INT.csv', index_col='Unnamed: 0')

In [ ]:
results_df

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt

metrics = ["Validation Accuracy", "Sensitivity", "Specificity"]
sns.set(style="whitegrid", palette="pastel", font_scale=1.2)

results_df['Group'] = results_df['Model'].str.split('_').str[0]  # Modrl_name 
results_df['Microbiome Data'] = results_df['Model'].str.split('_').str[1]  # Base or Taxa

metric_titles = {
    "Validation Accuracy": "Accuracy",
    "Sensitivity": "Sensitivity",
    "Specificity": "Specificity"
}

group_labels = {
    "Alpha": "ALL",
    "Beta": "ALL-A",
    "Omicron": "G+CC",
    "Pi": "CC"
}

palette = {
    "Base": "gray",      
    "WithTaxa": "#2ecc71"  
}

fig, axes = plt.subplots(1, len(metrics), figsize=(18, 6), sharey=True)

for idx, metric in enumerate(metrics):
    sns.boxplot(
        data=results_df, 
        x=metric, 
        y="Group", 
        hue="Microbiome Data", 
        dodge=True, 
        ax=axes[idx], 
        orient="h", 
        palette=palette
    )

    axes[idx].set_title(metric_titles.get(metric, metric))  
    axes[idx].set_xlabel(None)

    if idx == 0:
        axes[idx].set_ylabel("Model Group")
        axes[idx].set_yticklabels([group_labels.get(label.get_text(), label.get_text()) for label in axes[idx].get_yticklabels()])
    else:
        axes[idx].set_ylabel("")
    axes[idx].set_xlim(0.0, 1.0)
    
    if idx < 2:  
        axes[idx].legend_.set_title(None)

plt.tight_layout()
plt.legend()
plt.savefig('result_df.png', bbox_inches='tight')
plt.show()

In [154]:
results_df.columns

Index(['Model', 'Seed', 'Mean CV Accuracy', 'Test Accuracy',
       'Validation Accuracy', 'Sensitivity', 'Specificity', 'CV Scores',
       'Group', 'Microbiome Data'],
      dtype='object')

In [176]:
model_mapping = {
    "Alpha_Base": "ALL",
    "Alpha_WithTaxa": "ALL (taxa)",
    "Beta_Base": "ALL - A",
    "Beta_WithTaxa": "ALL - A (taxa)",
    "Omicron_Base": "CC + G",
    "Omicron_WithTaxa": "CC + G (taxa)",
    "Pi_Base": "CC",
    "Pi_WithTaxa": "CC (taxa)"
}

results_df["Model"] = results_df["Model"].map(model_mapping)

results_df.rename(
    columns={
        "Validation Accuracy": "Accuracy", 
        "Sensitivity": "Sensitivity", 
        "Specificity": "Specificity"
    },
    inplace=True
)

In [177]:
results_df.groupby('Model')[['Accuracy', 'Sensitivity', 'Specificity']].mean()

                Accuracy  Sensitivity  Specificity
Model
ALL             0.907879     0.736957     0.999302
ALL (taxa)      0.884545     0.668696     1.000000
ALL - A         0.716970     0.249130     0.967209
ALL - A (taxa)  0.710000     0.216957     0.973721
CC              0.634545     0.177826     0.878837
CC (taxa)       0.685455     0.126087     0.984651
CC + G          0.663333     0.210435     0.905581
CC + G (taxa)   0.685000     0.125652     0.984186

In [61]:
result_table = results_df.groupby('Model')[['Accuracy', 'Sensitivity', 'Specificity']].mean()

In [62]:
result_table.to_csv('result_table.csv')

    DATA: meta.caret.im

    변수:
    PET_amyloid (combined.Centiloid)
    CSF.ratio.ab42.ab40 (LUMIPULSE_CSF.ab42.ab40.ratio)
    PET.Tau (Tauopathy)
    CSF.ptau (LUMIPULSE_CSF_pTau)
    CSF.ttau (LUMIPULSE_CSF_tTau)
    WMH_volume
    Cort.Signature (CortSig_Thickness)
    Hippocampus.Volume (MR_LV_RV_HIPPOCAMPUS)
    Polygenic.Risk.Score
    APOE4.status (e4.pos 또는 e4.neg)
    Age
    Sex (Male 또는 Female)
    Race (Black, White, Other)
    Years.Education
    BMI
    Hypertension (ht.yes 또는 ht.no)
    Diabetes (dia.yes 또는 dia.no)
    IntervalDays.PET (INT_PET)
    IntervalDays.CSF (INT_CSF)
    IntervalDays.MRI (INT_MRI)
    amyloid.positive.AF (healthy 또는 preclinical), 클래스 라벨로 사용됨

In [ ]:
# Update factor levels for ease of interpretation 
meta.caret2 <- meta.caret2 %>% 
                  mutate(APOE4.status = ifelse(APOE4.status == "e4+", "e4.pos", "e4.neg"),
                         Sex = ifelse(Sex == "1", "Male", "Female"),
                         Race = ifelse(Race == "4", "Black", 
                                       ifelse(Race == "5", "White", "Other")),
                         Hypertension = ifelse(Hypertension == "1", 'ht.yes', 'ht.no'),
                         Diabetes = ifelse(Diabetes == "1", 'dia.yes', 'dia.no'),
                         amyloid.positive.AF = ifelse(amyloid.positive.AF == "0", "healthy", "preclinical"))

In [33]:
s1.columns

Index(['Participant', 'Stool_Date_Collected', 'Age', 'Sex', 'Race',
       'Years Education', 'CDR.testdate', 'CDR', 'CSF_LP_DATE',
       'LUMIPULSE_CSF.ab42.ab40.ratio', 'LUMIPULSE_CSF_tTau',
       'LUMIPULSE_CSF_pTau', 'PET_Date_pib', 'Days.SincePETpib',
       'pib_fsuvr_rsf_tot_cortmean', 'Centiloid.PiB', 'PET_Date_av45',
       'Days.SincePETav45', 'av45_fsuvr_rsf_tot_cortmean', 'Centiloid.AV45',
       'combined.PET_Date', 'Tracer2Use', 'combined.Centiloid',
       'amyloid.positive.AF', 'PET_TAU_Date', 'Tauopathy', 'tau.positive.AF',
       'MRI_Date', 'CortSig_Thickness', 'MR_LV_RV_HIPPOCAMPUS', 'WMH_volume',
       'APOE', 'APOE4.status', 'Polygenic Risk Score', 'INT_PET', 'INT_CSF',
       'INT_MRI', 'INT_CDR', 'Interval_Measure_Amyloid',
       'Interval_Days_Amyloid', 'WEIGHT.lb', 'HEIGHT.in', 'BMI', 'Cancer',
       'Active.Depression', 'Hypercholesterolemia', 'Hypertension', 'Diabetes',
       'Liver.Disease', 'Alcohol.Abuse', 'Tobacco.Use.PastOrPresent',
       'Autoimmune.Disorder', 'Thyroid.Disease', 'Cardiovascular.Disease',
       'Reads', 'Richness', 'Shannon', 'Tax.PCoA1', 'Tax.PCoA2', 'FBratio',
       'Fnl.Richness', 'Fnl.Shannon', 'Fnl.PCoA1', 'Fnl.PCoA2'],
      dtype='object')

In [42]:
s1_re = s1.loc[:, ['amyloid.positive.AF', 'combined.Centiloid', 'LUMIPULSE_CSF.ab42.ab40.ratio', 'Tauopathy', 'LUMIPULSE_CSF_pTau', 'LUMIPULSE_CSF_tTau', 'WMH_volume', 'CortSig_Thickness', 'MR_LV_RV_HIPPOCAMPUS', 'APOE4.status', 'Age', 'Sex', 'Race', 'BMI', 'Hypertension', 'Diabetes', 'INT_PET', 'INT_CSF', 'INT_MRI', 'Polygenic Risk Score', 'Years Education', ]]

In [ ]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

numeric_s1 = s1_re.select_dtypes(include=['number'])
correlation_matrix = numeric_s1.corr()

plt.figure(figsize=(12, 10))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f")
plt.title("Correlation Heatmap")
plt.show()

### 변수 범주화

In [ ]:
rf_meta['APOE4.status'] = np.where(rf_meta['APOE4.status'] == "e4+", "e4.pos", "e4.neg")
rf_meta['Sex'] = np.where(rf_meta['Sex'] == "1", "Male", "Female")
rf_meta['Race'] = np.where(rf_meta['Race'] == "4", "Black", 
                           np.where(rf_meta['Race'] == "5", "White", "Other"))
rf_meta['Hypertension'] = np.where(rf_meta['Hypertension'] == "1", 'ht.yes', 'ht.no')
rf_meta['Diabetes'] = np.where(rf_meta['Diabetes'] == "1", 'dia.yes', 'dia.no')
rf_meta['amyloid.positive.AF'] = np.where(rf_meta['amyloid.positive.AF'] == "0", "healthy", "preclinical")

In [ ]:
meta_data_info.iloc[53, 0] = 'Cardiovascular.Disease'

In [ ]:
columns = [
    'Active.Depression', 'Alcohol.Abuse', 'Tobacco.Use.PastOrPresent', 
    'Autoimmune.Disorder', 'Cardiovascular.Disease'
]

In [ ]:
for col in columns:
    rf_meta[col] = np.where(rf_meta[col] == 1, 'yes', 'no')